config/routes.rb
Rails.application.routes.draw do
  namespace :patients_backoffice do
    get 'dashboard/index'
  end
  namespace :doctors_backoffice do
    get 'dashboard/index'
  end
  resources :appointments, only: %i[index edit new update]

  namespace :patients_backoffice do
    resources :patients
  end
  namespace :doctors_backoffice do
    resources :doctors
  end
  devise_for :patients
  devise_for :doctors
  get 'welcome/index'

  root to: 'doctors_backoffice/dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
require 'time'
require 'active_support'

class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  validates :starts_at, :ends_at, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :crm, :crm_uf, presence: true

  scope :search_by, lambda { |doctor|
    where(doctor)
  }
end

app/models/patient.rb
require 'date'

class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :birth_date, :cpf, presence: true

  def age(birth)
    now = Time.now.utc.to_date
    now.year - birth.year - (now.month > birth.month || (now.month == birth.month && now.day >= birth.day) ? 0 : 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_class == Doctor
      'doctor_devise'
    elsif devise_controller? && resource_class == Patient
      'patient_devise'
    else
      'application'
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  layout 'appointments'

  def home
    @appointments = Appointment.where(doctor_id: nil, patient_id: nil)
  end

  def index
    @appointments = Appointment.all.page(params[:page]).per(10)
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(params_appointment)
    if @appointment.save!
      redirect_to appointments_path, notice: 'Médico criado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @appointment.update(params_appointment)
      redirect_to appointments_path, notice: 'Médico atualizado com sucesso!'
    else
      render :edit
    end
  end

  private

  def params_appointment
    params.require(:appointment).permit(:starts_at, :ends_at, doctor_id, patient_id)
  end

  def event_params
    if !!params[:event] && (params[:event]['start_at(4i)'].present? || params[:event]['start_at(5i)'].present?)

      start_at_date = if params[:event][:start_at_date].present?
                        params[:event][:start_at_date]
                      else
                        Date.today
                      end
      year  = start_at_date.match(%r{^(\d{4})[\-/]})[1]
      month = start_at_date.match(%r{[\-/](\d{2})[\-/]})[1]
      day   = start_at_date.match(%r{[\-/](\d{2})$})[1]
      params[:event]['start_at(1i)'] = year
      params[:event]['start_at(2i)'] = month
      params[:event]['start_at(3i)'] = day
    end
  end

  def params_date
    appointment = Datetime.now
    appointment.strftime
  end
end

app/controllers/doctors_backoffice/dashboard_controller.rb
class DoctorsBackoffice::DashboardController < DoctorsBackofficeController
  def index; end
end

app/controllers/doctors_backoffice/doctors_controller.rb
class DoctorsBackoffice::DoctorsController < DoctorsBackofficeController
  before_action :password_verify, only: [:update]
  before_action :set_doctor, only: %i[edit update destroy]

  def index
    @doctors = Doctor.all.page(params[:page]).per(10)
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(params_doctor)
    if @doctor.save!
      redirect_to doctors_backoffice_doctors_path, notice: 'Médico criado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @doctor.update(params_doctor)
      redirect_to doctors_backoffice_doctors_path, notice: 'Médico atualizado com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    if @doctor.destroy
      redirect_to doctors_backoffice_doctors_path, notice: 'Médico excluído com sucesso!'
    else
      render :index
    end
  end

  private

  def params_doctor
    params.require(:doctor).permit(:name, :email, :crm, :crm_uf, :password, :password_confirmation)
  end

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def password_verify
    if params[:doctor][:password].blank? && params[:doctor][:password_confirmation].blank?
      params[:doctor].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/doctors_backoffice_controller.rb
class DoctorsBackofficeController < ApplicationController
  before_action :authenticate_doctor!
  layout 'doctors_backoffice'
end

app/controllers/patients_backoffice/dashboard_controller.rb
class PatientsBackoffice::DashboardController < PatientsBackofficeController
  def index; end
end

app/controllers/patients_backoffice/patients_controller.rb
class PatientsBackoffice::PatientsController < PatientsBackofficeController
  before_action :password_verify, only: [:update]
  before_action :set_patient, only: %i[edit update destroy]

  def index
    @patients = Patient.all.page(params[:page]).per(10)
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(params_patient)
    if @patient.save!
      redirect_to patients_backoffice_patients_path, notice: 'Paciente criado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @patient.update(params_patient)
      redirect_to patients_backoffice_patients_path, notice: 'Paciente atualizado com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    if @patient.destroy
      redirect_to patients_backoffice_patients_path, notice: 'Paciente excluído com sucesso!'
    else
      render :index
    end
  end

  private

  def params_patient
    params.require(:patient).permit(:name, :email, :birth_date, :cpf, :password, :password_confirmation)
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def password_verify
    if params[:patient][:password].blank? && params[:patient][:password_confirmation].blank?
      params[:patient].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/patients_backoffice_controller.rb
class PatientsBackofficeController < ApplicationController
  before_action :authenticate_patient!
  layout 'patients_backoffice'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_backoffice/dashboard_helper.rb
module DoctorsBackoffice::DashboardHelper
end

app/helpers/doctors_backoffice/doctors_helper.rb
module DoctorsBackoffice::DoctorsHelper
end

app/helpers/doctors_backoffice_helper.rb
module DoctorsBackofficeHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_backoffice/dashboard_helper.rb
module PatientsBackoffice::DashboardHelper
end

app/helpers/patients_backoffice/patients_helper.rb
module PatientsBackoffice::PatientsHelper
end

app/helpers/patients_backoffice_helper.rb
module PatientsBackofficeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/doctors/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/doctors/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/doctors_backoffice/dashboard/index.html.erb
<div class="row">
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          Pacientes agendados (mês)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">100</div>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Earnings (Annual) Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                          Pacientes atendidos (hoje)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">15</div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Pending Requests Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                          Pacientes pendentes</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<br>

app/views/doctors_backoffice/doctors/edit.html.erb
<h1>Editando Médico</h1>
<%= form_with(model: [ :doctors_backoffice, @doctor ]) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter nome" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter email" %>
  </div>
  <div class="form-group">
    <%= form.label :crm %>
    <%= form.text_field :crm, class:"form-control", placeholder:"Enter CRM" %>
  </div>
  <div class="form-group">
    <%= form.label :crm_uf %>
    <%= form.text_field :crm_uf, class:"form-control", placeholder:"Enter CRM-UF" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Senha" %>
  </div>
  <div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de Senha" %>
  </div>
  <br>
  <div class="form-group">
    <%= link_to "Voltar", doctors_backoffice_doctors_path, class:"btn btn-outline-secondary" %>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
<% end %>

app/views/doctors_backoffice/doctors/index.html.erb
<h3>Lista de Médicos</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome Completo</th>
      <th scope="col">E-mail</th>
      <th scope="col">CRM</th>
      <th scope="col">CRM/UF</th>
      <th scope="col">
        <%= link_to new_doctors_backoffice_doctor_path, class:"btn btn-primary btn-success btn-sm" do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @doctors.each do |doctor| %>
    <tr>
      <th scope="row"><%= doctor.id %></th>
      <td><%= doctor.name %></td>
      <td><%= doctor.email %></td>
      <td><%= doctor.crm %></td>
      <td><%= doctor.crm_uf %></td>
      <td>
        <%= link_to edit_doctors_backoffice_doctor_path(doctor), class:"btn btn-primary btn-circle btn-sm" do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to doctors_backoffice_doctor_path(doctor), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: { confirm: "Realmente deseja excluir médico!"} do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @doctors %>

app/views/doctors_backoffice/doctors/new.html.erb
<h1>Novo Médico</h1>
<%= form_with(model: [ :doctors_backoffice, @doctor ]) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter nome" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter email" %>
  </div>
  <div class="form-group">
    <%= form.label :crm %>
    <%= form.text_field :crm, class:"form-control", placeholder:"Enter CRM" %>
  </div>
  <div class="form-group">
    <%= form.label :crm_uf %>
    <%= form.text_field :crm_uf, class:"form-control", placeholder:"Enter CRM-UF" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Senha" %>
  </div>
  <div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de Senha" %>
  </div>
  <br>
  <div class="form-group">
    <%= link_to "Voltar", doctors_backoffice_doctors_path, class:"btn btn-outline-secondary"%>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
<% end %>

app/views/doctors_backoffice/doctors/shared/_form.html.erb
<%= form_with(model: [ :doctors_backoffice, @doctor ]) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter nome" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter email" %>
  </div>
  <div class="form-group">
    <%= form.label :crm %>
    <%= form.text_field :crm, class:"form-control", placeholder:"Enter CRM" %>
  </div>
  <div class="form-group">
    <%= form.label :crm_uf %>
    <%= form.text_field :crm_uf, class:"form-control", placeholder:"Enter CRM-UF" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Senha" %>
  </div>
  <div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de Senha" %>
  </div>
  <br>
  <%= link_to "Voltar", doctors_backoffice_doctors_path, class:"btn btn-outline-secondary"%>
  <button type="submit" class="btn btn-primary">Salvar</button>
<% end %>

app/views/patients/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/patients/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/patients_backoffice/dashboard/index.html.erb
<div class="row">
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          Pacientes agendados (mês)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">100</div>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Earnings (Annual) Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                          Pacientes atendidos (hoje)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">15</div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Pending Requests Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                          Pacientes pendentes</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<br>

app/views/patients_backoffice/patients/edit.html.erb
<h1>Editando Pacientes</h1>
<%= form_with(model: [ :patients_backoffice, @patient ]) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter nome" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter email" %>
  </div>
  <div class="form-group">
    <%= form.label :birth_date %>
    <%= form.text_field :birth_date, class:"form-control", placeholder:"Enter Idade" %>
  </div>
  <div class="form-group">
    <%= form.label :cpf %>
    <%= form.text_field :cpf, class:"form-control", placeholder:"Enter CPF" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Senha" %>
  </div>
  <div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de Senha" %>
  </div>
  <br>
  <%= link_to "Voltar", patients_backoffice_patients_path, class:"btn btn-outline-secondary"%>
  <button type="submit" class="btn btn-primary">Salvar</button>
<% end %>

app/views/patients_backoffice/patients/index.html.erb
<h3>Lista de Pacientes</h3>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome Completo</th>
      <th scope="col">E-mail</th>
      <th scope="col">Idade</th>
      <th scope="col">CPF</th>
      <th scope="col">
        <%= link_to new_patients_backoffice_patient_path, class:"btn btn-primary btn-success btn-sm" do %>
          <i class="fas fa-plus"></i>
        <% end %>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
    <tr>
      <th scope="row"><%= patient.id %></th>
      <td><%= patient.name %></td>
      <td><%= patient.email %></td>
      <td><%= patient.birth_date %></td>
      <td><%= patient.cpf %></td>
      <td>
        <%= link_to edit_patients_backoffice_patient_path(patient), class:"btn btn-primary btn-circle btn-sm" do %>
          <i class="fas fa-edit"></i>
        <% end %>
        <%= link_to patients_backoffice_patient_path(patient), method: :delete, class:"btn btn-danger btn-circle btn-sm", data: { confirm: "Realmente deseja excluir paciente!"} do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @patients %>
  

app/views/patients_backoffice/patients/new.html.erb
<h1>Novo Paciente</h1>
<%= form_with(model: [ :patients_backoffice, @patient ]) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter nome" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter email" %>
  </div>
  <div class="form-group">
    <%= form.label :birth_date %>
    <%= form.date_field :birth_date, class:"form-control", placeholder:"" %>
  </div>
  <div class="form-group">
    <%= form.label :cpf %>
    <%= form.number_field :cpf, class:"form-control", placeholder:"Somente números" %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Senha" %>
  </div>
  <div class="form-group">
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Confirmação de Senha" %>
  </div>
  <br>
  <div class="form-group">
    <%= link_to "Voltar", patients_backoffice_patients_path, class:"btn btn-outline-secondary"%>
    <button type="submit" class="btn btn-primary">Salvar</button>
  </div>
<% end %>