config/routes.rb
Rails.application.routes.draw do
  namespace :patients_backoffice do
    get 'dashboard/index'
  end
  namespace :doctors_backoffice do
    get 'dashboard/index'
  end
  resources :appointments, only: %i[index edit new update]

  namespace :patients_backoffice do
    resources :patients
  end
  namespace :doctors_backoffice do
    resources :doctors
  end
  devise_for :patients
  devise_for :doctors
  get 'welcome/index'

  root to: 'doctors_backoffice/dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
require 'time'
require 'active_support'

class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor

  validates :starts_at, :ends_at, presence: true
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :crm, :crm_uf, presence: true

  scope :search_by, lambda { |doctor|
    where(doctor)
  }
end

app/models/patient.rb
require 'date'

class Patient < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :birth_date, :cpf, presence: true

  def age(birth)
    now = Time.now.utc.to_date
    now.year - birth.year - (now.month > birth.month || (now.month == birth.month && now.day >= birth.day) ? 0 : 1)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller? && resource_class == Doctor
      'doctor_devise'
    elsif devise_controller? && resource_class == Patient
      'patient_devise'
    else
      'application'
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  layout 'appointments'

  def home
    @appointments = Appointment.where(doctor_id: nil, patient_id: nil)
  end

  def index
    @appointments = Appointment.all.page(params[:page]).per(10)
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(params_appointment)
    if @appointment.save!
      redirect_to appointments_path, notice: 'Médico criado com sucesso!'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @appointment.update(params_appointment)
      redirect_to appointments_path, notice: 'Médico atualizado com sucesso!'
    else
      render :edit
    end
  end

  private

  def params_appointment
    params.require(:appointment).permit(:starts_at, :ends_at, doctor_id, patient_id)
  end

  def event_params
    if !!params[:event] && (params[:event]['start_at(4i)'].present? || params[:event]['start_at(5i)'].present?)

      start_at_date = if params[:event][:start_at_date].present?
                        params[:event][:start_at_date]
                      else
                        Date.today
                      end
      year  = start_at_date.match(%r{^(\d{4})[\-/]})[1]
      month = start_at_date.match(%r{[\-/](\d{2})[\-/]})[1]
      day   = start_at_date.match(%r{[\-/](\d{2})$})[1]
      params[:event]['start_at(1i)'] = year
      params[:event]['start_at(2i)'] = month
      params[:event]['start_at(3i)'] = day
    end
  end

  def params_date
    appointment = Datetime.now
    appointment.strftime
  end
end

app/controllers/doctors_backoffice_controller.rb
class DoctorsBackofficeController < ApplicationController
  before_action :authenticate_doctor!
  layout 'doctors_backoffice'
end

app/controllers/patients_backoffice_controller.rb
class PatientsBackofficeController < ApplicationController
  before_action :authenticate_patient!
  layout 'patients_backoffice'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_backoffice/dashboard_helper.rb
module DoctorsBackoffice::DashboardHelper
end

app/helpers/doctors_backoffice/doctors_helper.rb
module DoctorsBackoffice::DoctorsHelper
end

app/helpers/doctors_backoffice_helper.rb
module DoctorsBackofficeHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_backoffice/dashboard_helper.rb
module PatientsBackoffice::DashboardHelper
end

app/helpers/patients_backoffice/patients_helper.rb
module PatientsBackoffice::PatientsHelper
end

app/helpers/patients_backoffice_helper.rb
module PatientsBackofficeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/consultas/index.erb
<div class="row">
  <!-- Earnings (Monthly) Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-primary shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                          Pacientes agendados (mês)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">100</div>
                  </div>
                  <div class="col-auto">
                      <i class="fas fa-calendar fa-2x text-gray-300"></i>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Earnings (Annual) Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                          Pacientes atendidos (hoje)</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">15</div>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!-- Pending Requests Card Example -->
  <div class="col-xl-4 col-md-6 mb-4">
      <div class="card border-left-warning shadow h-100 py-2">
          <div class="card-body">
              <div class="row no-gutters align-items-center">
                  <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                          Pacientes pendentes</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800">18</div>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthDoctor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/appointments.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>HealthDoctor</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application' %>
		<%= stylesheet_link_tag 'appointments' %>
		
		
	</head>
	<body id="page-top">
		<!-- Page Wrapper -->
		<div id="wrapper">

				<!-- Sidebar -->
				<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
					<!-- Sidebar - Brand -->
					<%= link_to doctors_backoffice_dashboard_index_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
						<div class="sidebar-brand-icon rotate-n-15">
								<i class="fas fa-stethoscope"></i>
						</div>
						<div class="sidebar-brand-text mx-3">HealthDoctor</div>
					<% end %>

					<!-- Divider -->
					<hr class="sidebar-divider my-0">

					<!-- Nav Item - Dashboard -->
					<li class="nav-item">
						<%= link_to  doctors_backoffice_dashboard_index_path, class: "nav-link" do %>
							<i class="fas fa-tachometer-alt"></i>
							<span>Dashboard</span>
						<% end %>
					</li>
					<!-- Nav Item - Doctor -->
					<li class="nav-item">
						<%= link_to  doctors_backoffice_doctors_path, class: "nav-link" do %>
							<i class="fas fa-user-md"></i>
							<span>Médicos</span>
						<% end %>
					</li>
					<!-- Nav Item - Patient -->
					<li class="nav-item">
						<%= link_to  patients_backoffice_patients_path, class: "nav-link" do %>
							<i class="fas fa-hospital-user"></i>
							<span>Pacientes</span>
						<% end %>
					</li>
					<!-- Nav Item - Appointments -->
					<li class="nav-item">
						<%= link_to  appointments_path, class: "nav-link" do %>
							<i class="fas fa-calendar-alt"></i>
							<span>Agendar Consulta</span>
						<% end %>
					</li>
				</ul>
				<!-- End of Sidebar -->

				<!-- Content Wrapper -->
				<div id="content-wrapper" class="d-flex flex-column">

						<!-- Main Content -->
						<div id="content">

								<!-- Topbar -->
								<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

										<!-- Sidebar Toggle (Topbar) -->
										<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
												<i class="fa fa-bars"></i>
										</button>

										<!-- Topbar Navbar -->
										<ul class="navbar-nav ml-auto">
											<!-- Nav Item - Search Dropdown (Visible Only XS) -->
											<li class="nav-item dropdown no-arrow d-sm-none">
													<a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
															data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
															<i class="fas fa-search fa-fw"></i>
													</a>
													<!-- Dropdown - Messages -->
													<div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
															aria-labelledby="searchDropdown">
															<form class="form-inline mr-auto w-100 navbar-search">
																	<div class="input-group">
																			<input type="text" class="form-control bg-light border-0 small"
																					placeholder="Search for..." aria-label="Search"
																					aria-describedby="basic-addon2">
																			<div class="input-group-append">
																					<button class="btn btn-primary" type="button">
																							<i class="fas fa-search fa-sm"></i>
																					</button>
																			</div>
																	</div>
															</form>
													</div>
											</li>
											<div class="topbar-divider d-none d-sm-block"></div>
											<li class="nav-item dropdown no-arrow">
													<%= link_to "Logout", destroy_doctor_session_path, class:"fas fa-sign-out-alt fa-sm fa-fw mr-5 text-gray-400"%>
																							
											</li>
										</ul>
								</nav>
								<div class="container-fluid">
									<%= yield %>
								</div>
						</div>
				</div>
		</div>

		
		<!-- Logout Modal-->
		<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
						<button class="close" type="button" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">×</span>
						</button>
					</div>
					<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
					<div class="modal-footer">
						<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
						<a class="btn btn-primary" href="login.html">Logout</a>
					</div>
				</div>
			</div>
		</div>
		<%= javascript_pack_tag 'application' %>
		<%= javascript_pack_tag 'appointments' %>
	
		<% if notice %>
			<%= javascript_tag do %>
        $.bootstrapGrowl('<%= notice %>', {
        type: 'success', // (null, 'info', 'danger', 'success')
        offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
        align: 'right', // ('left', 'right', or 'center')
        allow_dismiss: true, // If true then will display a cross to close the popup.
        stackup_spacing: 10 // spacing between consecutively stacked growls.
        });
      <% end %>
		<% end %>

		<%= javascript_tag do %>      
			$(function() {        
				$('.datepicker').datepicker();      
			});    
		<% end %>
	</body>
</html>

app/views/layouts/doctor_devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthDoctor</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
		<%= stylesheet_link_tag 'doctor_devise' %>
  </head>
	<body class="bg-gradient-primary">
		<div class="container">
			<%= yield %>
		</div>
		<%= javascript_pack_tag 'application' %>
		<%= javascript_pack_tag 'doctor_devise' %>
	</body>
</html>

app/views/layouts/doctors_backoffice.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>HealthDoctor</title>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta name="description" content="">
		<meta name="author" content="">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application' %>
		<%= stylesheet_link_tag 'doctors_backoffice' %>
		
		
	</head>
	<body id="page-top">
		<!-- Page Wrapper -->
		<div id="wrapper">

				<!-- Sidebar -->
				<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
					<!-- Sidebar - Brand -->
					<%= link_to doctors_backoffice_dashboard_index_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
						<div class="sidebar-brand-icon rotate-n-15">
								<i class="fas fa-stethoscope"></i>
						</div>
						<div class="sidebar-brand-text mx-3">HealthDoctor</div>
					<% end %>

					<!-- Divider -->
					<hr class="sidebar-divider my-0">

					<!-- Nav Item - Dashboard -->
					<li class="nav-item">
						<%= link_to  doctors_backoffice_dashboard_index_path, class: "nav-link" do %>
							<i class="fas fa-tachometer-alt"></i>
							<span>Dashboard</span>
						<% end %>
					</li>
					<!-- Nav Item - Doctor -->
					<li class="nav-item">
						<%= link_to  doctors_backoffice_doctors_path, class: "nav-link" do %>
							<i class="fas fa-user-md"></i>
							<span>Médicos</span>
						<% end %>
					</li>
					<!-- Nav Item - Patient -->
					<li class="nav-item">
						<%= link_to  patients_backoffice_patients_path, class: "nav-link" do %>
							<i class="fas fa-hospital-user"></i>
							<span>Pacientes</span>
						<% end %>
					</li>
					<!-- Nav Item - Appointments -->
					<li class="nav-item">
						<%= link_to  appointments_path, class: "nav-link" do %>
							<i class="fas fa-calendar-alt"></i>
							<span>Agendar Consulta</span>
						<% end %>
					</li>
				</ul>
				<!-- End of Sidebar -->

				<!-- Content Wrapper -->
				<div id="content-wrapper" class="d-flex flex-column">

						<!-- Main Content -->
						<div id="content">

								<!-- Topbar -->
								<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

										<!-- Sidebar Toggle (Topbar) -->
										<button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
												<i class="fa fa-bars"></i>
										</button>


										<!-- Topbar Navbar -->
										<ul class="navbar-nav ml-auto">
											<!-- Nav Item - Search Dropdown (Visible Only XS) -->
											<li class="nav-item dropdown no-arrow d-sm-none">
													<a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
															data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
															<i class="fas fa-search fa-fw"></i>
													</a>
													<!-- Dropdown - Messages -->
													<div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
															aria-labelledby="searchDropdown">
															<form class="form-inline mr-auto w-100 navbar-search">
																	<div class="input-group">
																			<input type="text" class="form-control bg-light border-0 small"
																					placeholder="Search for..." aria-label="Search"
																					aria-describedby="basic-addon2">
																			<div class="input-group-append">
																					<button class="btn btn-primary" type="button">
																							<i class="fas fa-search fa-sm"></i>
																					</button>
																			</div>
																	</div>
															</form>
													</div>
											</li>
											<div class="topbar-divider d-none d-sm-block"></div>
											<li class="nav-item dropdown no-arrow">
													<%= link_to "Logout", destroy_doctor_session_path, class:"fas fa-sign-out-alt fa-sm fa-fw mr-5 text-gray-400"%>
																							
											</li>
										</ul>
								</nav>
								<div class="container-fluid">
									<%= yield %>
								</div>
						</div>
				</div>
		</div>

		
		<!-- Logout Modal-->
		<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
						<button class="close" type="button" data-dismiss="modal" aria-label="Close">
							<span aria-hidden="true">×</span>
						</button>
					</div>
					<div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
					<div class="modal-footer">
						<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
						<a class="btn btn-primary" href="login.html">Logout</a>
					</div>
				</div>
			</div>
		</div>
		<%= javascript_pack_tag 'application' %>
		<%= javascript_pack_tag 'doctors_backoffice' %>
	
		<% if notice %>
			<%= javascript_tag do %>
        $.bootstrapGrowl('<%= notice %>', {
        type: 'success', // (null, 'info', 'danger', 'success')
        offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
        align: 'right', // ('left', 'right', or 'center')
        allow_dismiss: true, // If true then will display a cross to close the popup.
        stackup_spacing: 10 // spacing between consecutively stacked growls.
        });
      <% end %>
		<% end %>
	</body>
</html>

app/views/layouts/patient_devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthDoctor</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
		<%= stylesheet_link_tag 'patient_devise' %>
  </head>
	<body class="bg-gradient-primary">
		<div class="container">
			<%= yield %>
		</div>
		<%= javascript_pack_tag 'application' %>
		<%= javascript_pack_tag 'patient_devise' %>
	</body>
</html>

app/views/layouts/patients_backoffice.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>HealthDoctor</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application' %>
    <%= stylesheet_link_tag 'patients_backoffice' %>
    
    
  </head>
  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
          <!-- Sidebar - Brand -->
          <%= link_to patients_backoffice_dashboard_index_path, class: "sidebar-brand d-flex align-items-center justify-content-center" do %>
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-stethoscope"></i>
            </div>
            <div class="sidebar-brand-text mx-3">HealthDoctor</div>
          <% end %>

          <!-- Divider -->
          <hr class="sidebar-divider my-0">

          <!-- Nav Item - Dashboard -->
          <li class="nav-item">
            <%= link_to  patients_backoffice_dashboard_index_path, class: "nav-link" do %>
              <i class="fas fa-tachometer-alt"></i>
              <span>Dashboard</span>
            <% end %>
          </li>
          <!-- Nav Item - Doctor -->
          <li class="nav-item">
            <%= link_to  doctors_backoffice_doctors_path, class: "nav-link" do %>
              <i class="fas fa-user-md"></i>
              <span>Médicos</span>
            <% end %>
          </li>
          <!-- Nav Item - Patient -->
          <li class="nav-item">
            <%= link_to  patients_backoffice_patients_path, class: "nav-link" do %>
              <i class="fas fa-hospital-user"></i>
              <span>Pacientes</span>
            <% end %>
          </li>
          <!-- Nav Item - Appointments -->
					<li class="nav-item">
						<%= link_to  appointments_path, class: "nav-link" do %>
							<i class="fas fa-calendar-alt"></i>
							<span>Agendar Consulta</span>
						<% end %>
					</li>
        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>


                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">
                      <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                      <li class="nav-item dropdown no-arrow d-sm-none">
                          <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              <i class="fas fa-search fa-fw"></i>
                          </a>
                          <!-- Dropdown - Messages -->
                          <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                              aria-labelledby="searchDropdown">
                              <form class="form-inline mr-auto w-100 navbar-search">
                                  <div class="input-group">
                                      <input type="text" class="form-control bg-light border-0 small"
                                          placeholder="Search for..." aria-label="Search"
                                          aria-describedby="basic-addon2">
                                      <div class="input-group-append">
                                          <button class="btn btn-primary" type="button">
                                              <i class="fas fa-search fa-sm"></i>
                                          </button>
                                      </div>
                                  </div>
                              </form>
                          </div>
                      </li>
                      <div class="topbar-divider d-none d-sm-block"></div>
                        <%= link_to "Logout", destroy_patient_session_path, class:"fas fa-sign-out-alt fa-sm fa-fw mr-5 text-gray-400"%>  
                      </li>
                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">

                    <!-- Page Heading -->
                    <%= yield %>

                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_pack_tag 'patients_backoffice' %>

  </body>
</html>